[versions]
loom = "1.5-SNAPSHOT" # todo bump to 1.7
junit = "4.13.2"
kotlin = "2.0.21"
kotlinx-coroutines = "1.9.0"

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
loom-legacy = { id = "legacy-looming", version.ref = "loom" }